include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules: 
    require_trailing_commas: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_print: true
